VizPanel: Allow queries to be cancelled
grafana/scenes pull request #220
Opened 2023-05-31 10:52 UTC by kaydelaney

Not sure this is the right approach (specifically with how I'm getting the closest SceneQueryRunner), but it seems to work.

Part of #207
Will tackle query variable cancellation in another PR

2023-05-31 12:57 UTC, dprokop commented on packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
> +  const queryRunner = getClosest(model, (s) => (s.state.$data instanceof SceneQueryRunner) ? s.state.$data : undefined);
Moving this to VizPanel end exposing `model.onCancelQuery` sounds like an optimal solution.

Another thing is how you retrieve the query runner. You should do that by using `sceneGraph.getData(...)` which will return an object implementing `SceneDataProvider` interface. This interface is currently implemented by three types of objects:
- `SceneQueryRunner`
- `SceneDataTransformer`
- `SceneDataNode`

I think we may want to extend the `SceneDataProvider` interface with a method that implements the cancellation. Thinking about this, especially for the reason that `SceneDataTransformer` can wrap `SceneQueryRunner` :

```
new SceneDataTransformer({
  $data: new SceneQeuryRunner(...),
  ...
});
```

So the cancellation can happen on SQR inderectly via SceneDataTransformer implementation.


The cancellation does not make sense for `SceneDataNode` tho, as this only provides static data to siblings.

2023-05-31 13:21 UTC, dprokop commented
Would appreciate a demo scene in scene-app for testing this behavior :)

2023-06-01 10:14 UTC, kaydelaney commented
> Would appreciate a demo scene in scene-app for testing this behavior :)

I think the lazy loading demo should work for testing (the queries take at least 5 seconds)

2023-06-01 14:19 UTC, dprokop requested changes

2023-06-01 14:19 UTC, dprokop commented on packages/scenes/src/querying/SceneQueryRunner.ts
> +  public cancel() {
Think we are missing implementation of `cancel` method for `SceneDataTransformer`

2023-06-01 14:39 UTC, kaydelaney commented on packages/scenes/src/querying/SceneQueryRunner.ts
> +  public cancel() {
Added. Haven't dealt with SceneDataTransformer before so let me know if the cancel method I added makes sense

2023-06-01 15:26 UTC, dprokop commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    this._transformSub?.unsubscribe();
@kaydelaney I don't think this is sufficient and also doesn't seem to work. What we need to unsubscribe from is the data subscription which we are setting in the activation handler and which is then subject of the transformation.

But, there are two paths here:
1. `SceneTransformationNode` that does not have `$data: new SceneQueryRunner(...)` defined and transforms the closest data provider.
2. `SceneTransformationNode` that has it's on SceneQueryRunner.

In 1) the source SQR can be shared between multiple panels and IMO the cancellation should only happen in the context of the current transformation node to avoid cancellation in other panels which I think can be confusing. I think we should not allow cancellation in such a scenario at all, WDYT?

In 2) the approach is similar to SQR cancellation - so that just cancels the closes SQR (available in transformation node via `this.getSourceData` method)

2023-06-01 15:38 UTC, kaydelaney commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    this._transformSub?.unsubscribe();
Ah, I see, thanks for the context. I think I agree that we shouldn't allow cancellation in the first scenario

2023-06-01 15:41 UTC, kaydelaney commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    this._transformSub?.unsubscribe();
btw, guessing SceneTransformationNode is a mistype and you meant SceneDataTransformer?

2023-06-06 10:32 UTC, kaydelaney commented
Not sure what the best approach is for checking if a SQR is shared between multiple panels

2023-06-07 06:27 UTC, torkelo commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +      } catch {}
why the try catch?

2023-06-07 10:01 UTC, kaydelaney commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +      } catch {}
I had it because getSourceData can throw, but I guess there's actually no need to wrap it

2023-06-14 12:28 UTC, torkelo commented on packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
> +  const canCancel = $data instanceof SceneQueryRunner || ($data instanceof SceneDataTransformer && $data.state.$data instanceof SceneQueryRunner);
@kaydelaney I would just check if $data exists, I don't think we need any of these instance of checks

2023-06-14 12:29 UTC, torkelo commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    }
we do not need this instanceof check, cancel is part of the SceneDataProvider interface

2023-06-14 12:30 UTC, torkelo commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    }
```suggestion
    if (this.state.$data) {
        this.state.$data.cancelQuery();
    }
```

2023-06-15 12:20 UTC, kaydelaney commented on packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
> +  const canCancel = $data instanceof SceneQueryRunner || ($data instanceof SceneDataTransformer && $data.state.$data instanceof SceneQueryRunner);
So, the instance checks are there for the case where $data is a SceneDataTransformer that doesn't have its "own" SceneQueryRunner. Since in this case the SceneQueryRunner could be shared by multiple panels, we didn't want to allow for cancellation as that would cancel other panels, which could be kind of weird. What do you think?

2023-06-15 13:20 UTC, torkelo commented on packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
> +  const canCancel = $data instanceof SceneQueryRunner || ($data instanceof SceneDataTransformer && $data.state.$data instanceof SceneQueryRunner);
I think that is fine (until we know otherwise) that it would also cancel results for other panels. 

if it becomes an issue we should probably add a "canCancel" or something to SceneDataProvider interface. These instance of checks make the framework less extensible so need to limit where we use them :)

2023-06-16 12:26 UTC, dprokop commented on packages/scenes/src/components/VizPanel/VizPanelRenderer.tsx
> +  const canCancel = $data instanceof SceneQueryRunner || ($data instanceof SceneDataTransformer && $data.state.$data instanceof SceneQueryRunner);
@kaydelaney I've pushed minor update to bring this behavior back.

2023-06-17 14:16 UTC, torkelo commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    if (this.getSourceData() instanceof SceneQueryRunner) {
Why the instance of check here?

2023-06-19 08:24 UTC, dprokop commented on packages/scenes/src/querying/SceneDataTransformer.ts
> +    if (this.getSourceData() instanceof SceneQueryRunner) {
We don't need it, just removed it

2023-06-19 10:03 UTC, merged