Autofit: Fit widget in the screen depending on the height
grafana/scenes pull request #658
Opened 2024-03-22 14:09 UTC by ivanortegaalba

2024-03-22 14:13 UTC, ivanortegaalba commented
Uploading Screenshare - 2024-03-22 3_12_54 PM.mp4…

2024-03-22 15:11 UTC, dprokop commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
This kind of feels wrong to have the autofit as a part of the core layour implementation. I think we should solve this as an addon to the `SceneGridLayout`. Maybe we could have a "hook" that one could pass to the ScenegGidLayout via state (sth like `processGridLayout`) that would be called from `buildGridLayout` when you call `cells = fitPanelsInHeight(cells, height);`.

Then that code would become:

```
if (this.state.processGridLayout) {
      cells = processGridLayout(cells, height);
    }
```

And then the Autofit would be a behavior implemented in Grafana core that would provide that layout processin and URL sync. WDYT @ivanortegaalba ?

2024-03-25 09:59 UTC, ivanortegaalba commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
Yep, that would work too. But I think it would be useful for a non-dashboard app that can be displayed in "TV Mode" or on a screen. So, having an option that says "fitContent" or "fitVertical" as a boolean would be easier since the size of the widget, the margins, the row height and everything else is managed by the core layout. Otherwise we need to export all those measures, and make them configurable, in order to properly configure the layout.

So, IMO, the simplest solution is to keep the manipulation at the core where all the params are set.

2024-03-26 10:03 UTC, natellium commented
Just coming in here to ask if this issue is still present in the new implementation https://github.com/grafana/grafana/issues/79313

2024-03-26 10:36 UTC, dprokop commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
Yes and no IMO - the manipulation is grid units only, building layout does not require any knowledge about measures like row height or gap. 

I see your point, tho I have not seen any asks from app plugin devs to add such an API. Not sure how realistic it is for the apps to be used in the TV mode, given they are way more interactive that a dashboard. 

Is there any way we can at least make the URL sync a core specific behavior? It feels very wrong to grids auto fit behavior to URL by default.

2024-03-26 11:19 UTC, ivanortegaalba commented
> Just coming in here to ask if this issue is still present in the new implementation [grafana/grafana#79313](https://github.com/grafana/grafana/issues/79313)

This issue is caused by not taking into account the height taken by the variables toolbar. This won't happen with this new approach, since the viewport is calculated as the size available on the screen, not fixing any height for the navbar or any other item out of the dashboard element. The old architecture, the calculation includes fixed values like the navbar.

2024-03-26 13:43 UTC, torkelo commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
We could also deprecate this legacy experimental feature and implement it more properly (with flex layout or some other more dynamic layout). 

But agree I do not think the core scenes lib needs to handle it

2024-03-26 23:46 UTC, ivanortegaalba commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
I am happy to mark it as `UNSAFE_fitPanels` to not invite you to use it, as we did with `UNSAFE_nowDelay`.

But at least we need to port it somehow, don't we?

2024-03-27 07:16 UTC, torkelo commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
> But I think it would be useful for a non-dashboard app that can be displayed in "TV Mode" or on a screen. 

apps do not use the absolute grid layout

2024-03-27 07:17 UTC, torkelo commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
I think all use FlexLayout or CSSGridLayout which can easily be made "autofit" with simple CSS

2024-03-27 07:19 UTC, torkelo commented on packages/scenes/src/components/layout/grid/SceneGridLayout.tsx
> +  }
but looking closer at the implementation, it is really nice place for the logic to sit in between the runtime grid model and the model we pass to the react-grid-layout  component 

so maybe an unsafe prop is ok

2024-04-01 13:45 UTC, mdvictor commented on packages/scenes/src/components/layout/grid/utils.ts
> +  console.log('scaleFactor', scaleFactor);
I think we can clean these logs here, right?

2024-04-01 14:34 UTC, mdvictor requested changes
I think there was an unintentional change maybe to the timer constructor?

2024-04-01 14:34 UTC, mdvictor commented on packages/scenes/src/behaviors/LiveNowTimer.ts
> +  public constructor({ enabled = false }) {
I think the refactor here has created a bug. Testing this out I can't open grafana:

![Screenshot 2024-04-01 at 17 28 59](https://github.com/grafana/scenes/assets/36818606/a610a0e0-0f8c-4476-b5b7-d16278afe5e0)

I think the constructor should be:
`public constructor(enabled = false)` not
` public constructor({ enabled = false })`

2024-04-02 10:46 UTC, mdvictor approved these changes
LGTM! Just need to remove those console.logs in `utils.ts` and I think it's good to go!

2024-04-02 12:23 UTC, ivanortegaalba commented on packages/scenes/src/components/layout/grid/utils.ts
> +  console.log('y');
```suggestion
```

2024-04-02 12:23 UTC, ivanortegaalba commented on packages/scenes/src/components/layout/grid/utils.ts
> +}
```suggestion
export function fitPanelsInHeight(cells: ReactGridLayout.Layout[], height: number) {
  // Take into account cell margint top + cell margin bottom + adding some marging at the bottom
  const visibleHeight = height - GRID_CELL_VMARGIN * 4;
  const currentGridHeight = Math.max(...cells.map((cell) => cell.h + cell.y));

  const visibleGridHeight = Math.floor(visibleHeight / (GRID_CELL_HEIGHT + GRID_CELL_VMARGIN));
  const scaleFactor = currentGridHeight / visibleGridHeight;

  return cells.map((cell) => {
    return {
      ...cell,
      y: Math.round(cell.y / scaleFactor) || 0,
      h: Math.round(cell.h / scaleFactor) || 1,
    };
  });
}
```

2024-04-02 12:31 UTC, merged