SafeSerializableSceneObject: Wrap only for supported Grafana version
grafana/scenes pull request #854
Opened 2024-07-31 14:09 UTC by dprokop

This PR brings backwards compatibility for `scopedVars.__sceneObject` and `SafeSerializableSceneObject`. (ref https://github.com/grafana/scenes/pull/828, https://github.com/grafana/scenes/issues/851)

With this change, Scenes apps using 5.7+ will be able to run smoothly in Grafana versions that do not contain https://github.com/grafana/grafana/pull/90833.

For versions that will have [this](https://github.com/grafana/grafana/pull/90833) included, that is :
11.2.x 
11.1.2+ (backport MERGED: https://github.com/grafana/grafana/pull/90837)
11.0.3+ (backport NOT MERGED YET: https://github.com/grafana/grafana/pull/91240)
10.4.7+ (backport NOT MERGED YET: https://github.com/grafana/grafana/pull/91242)

`scopedVars.__sceneObject` WILL use `SafeSerializableSceneObject`. For versions other than mentioned above, `scopedVars.__sceneObject` will be just an old good plan `ScopedVar`.

2024-08-05 07:05 UTC, oscarkilhed reviewed
It feels a bit backward to have the library change behavior depending on the version of what is using the library, but I can see this being the most pragmatic solution.

I think the code looks good, and the test coverage is there. I guess testing this manually on the grafana versions affected could be done when we're bumping scenes to this version.

2024-08-07 07:48 UTC, dprokop commented
> It feels a bit backward to have the library change behavior depending on the version of what is using the library, but I can see this being the most pragmatic solution.

Agree, but this feels best what we can do with a change like this. 

> I think the code looks good, and the test coverage is there. I guess testing this manually on the grafana versions affected could be done when we're bumping scenes to this version.

You can already test it with the canary release. I don't want to merge this until reviewers will run an app with this version agains versions we are building compatibility for.

2024-08-07 09:24 UTC, torkelo approved these changes

2024-08-14 07:08 UTC, torkelo commented
@dprokop any reason this is not merged?

2024-08-14 07:09 UTC, dprokop commented
@torkelo - yeah, didn't  get anyone's eyes for testing this yet. Asked the team to help with getting this landed as soon as possible.

2024-08-14 07:15 UTC, torkelo commented
@dprokop ah, I see. no worries, just going through PRs, wanted to make sure it was not forgotten

2024-08-14 10:33 UTC, axelavargas reviewed
I am helping with the testing part :), however, I left a small comment.

2024-08-14 10:33 UTC, axelavargas commented on packages/scenes/src/utils/wrapInSafeSerializableSceneObject.ts
> +    return false;
🤔 should we log a warning or something?  I remember sometimes we can have versions with this kind of pattern `11.0.0-preview`, for this cases it will not match the regex

2024-08-14 13:17 UTC, axelavargas commented on packages/scenes/src/utils/wrapInSafeSerializableSceneObject.test.ts
> +      'should return false for version higher than 10.4.7 version (%s)',
```suggestion
      'should return true for version higher than 10.4.7 version (%s)',
```

2024-08-16 14:21 UTC, axelavargas requested changes
Forgot to add the `request changes` :)

2024-08-19 09:32 UTC, dprokop commented
@axelavargas  - thanks for running this! I've made a version ranges mistake - 11.0.3 and 10.4.7 were **security** releases and those did not include the corresponding backports. I've update the version ranges to reflect the upcoming patch releases.

2024-08-19 10:14 UTC, axelavargas approved these changes
Tested with the latest changes and works as expected 🥳 , awesome work with this one, @dprokop

2024-08-19 12:59 UTC, merged