UrlSyncManager: Improvements and fixes
grafana/scenes pull request #96
Opened 2023-03-22 10:15 UTC by torkelo

@domasx2 identified some issues with URL sync when it comes to clearing / restoring state

* Restoring state if the initial state was undefined did not work 
* Coming back to a scene did not remember the initialStates (that is used to restore state when url does not contain the state), this required a change so that we do not new up a new UrlSyncManager every initUrlSync but instead preserve the same instance for as long as that scene exists.
* Also updated the tests to more accurately reflect usage (initUrlSync called, then scene is activated)

2023-03-22 10:56 UTC, domasx2 requested changes
I tried it, some new issues happen:

- On initial load data sources have defaults selected, page works, but data source variables are no longer populated to URL
- Descending into drill down populates url with empty data source variables, data sources become unselected and page breaks
- Bonus, also reproducible on main brach: On initial load data source vars have selected values, but clicking root item in breadcrumbs populates url with empty data source variables and unselects them

https://user-images.githubusercontent.com/847684/226882112-ce5b45db-132d-402a-adf9-7a3d468e9a6c.mp4

2023-03-22 11:21 UTC, torkelo commented
@domasx2 thanks for testing more, your drilldown link looks to contain has a `var-prometheus=`  , which is why it's blank on the drilldown view. So it looks like a bug in the link building?

2023-03-22 11:23 UTC, torkelo commented
@domasx2 
>  but data source variables are no longer populated to URL
If works for me, if you change a variable does not not get populated to the url? State -> Url only happens when you change the state (ie select a new variable value)

2023-03-22 11:35 UTC, domasx2 commented
> @domasx2 thanks for testing more, your drilldown link looks to contain a `var-prometheus=` , which is why it's blank on the drilldown view. So it looks like a bug in the link building?

The link we build has no query params, so I think `var-prometheus=` is set by scenes  
![image](https://user-images.githubusercontent.com/847684/226891847-8461663e-02c6-4e0b-bce9-a694c59df6e3.png)

> If works for me, if you change a variable does not not get populated to the url? State -> Url only happens when you change the state (ie select a new variable value)

2023-03-22 11:38 UTC, torkelo commented
@domasx2 ok, if your link is not preserving variables, they will be cleared to their initial state. But think that is a separate issue. 

The problem I am seeing is that variables are initially have no value, then get value (synced to url). But then when you move back to it without them in URL they get get reset to no value. 

Think this is very hard problem, (to know when a blank url state should clear the current state). Need to think more on this

2023-03-22 11:46 UTC, domasx2 commented
> @domasx2 ok, if your link is not preserving variables, they will be cleared to their initial state. But think that is a separate issue. 

To be clear, the link here preserves query params, it just does not insert `var-prometheus=` and etc if it wasn't present in url to begin with.

**On main branch:** On initial load data  ource variables have a default selected and are synced to the URL. Drilldown link copies query params, it works

**On this branch:** On initial load data source variables have a default selected but the default is not synced to the URL. Thus drilldown link has no query params, drilldown opens with empty data soruce variables and somehow empty values are then synced the URL,

It seems on initialization data source variables select first item from the list if available, but when being re-activated, reset to none if nothing is in URL?

2023-03-22 11:52 UTC, torkelo commented
@domasx2 Hm.. the inital values for the variables is en empty string, so this check https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/variants/MultiValueVariable.ts#L278 does not work (causing them to be cleared when they are not present in URL)

2023-03-22 11:54 UTC, domasx2 commented
Hm, gonna try explicitly specifying a default data source

2023-03-22 11:57 UTC, torkelo commented
@domasx2 yea, going to see how the system can know what what state to preserve and what to clear when value is not present in url, super hard. Also very hard with variables going through quick changes as scenes load causing lots of url syncs

2023-03-22 14:47 UTC, torkelo commented
@domasx2 pushed a big update, I had to remove a big feature or UrlSyncManager of being able to restore to an initial value in case the url keys are removed. Now this is passed to updateFromUrl with key values set to null, so it's up to each scene object for how to handle missing url keys, so for time range for example it will just ignore the updateFromUrl if there are not time range keys. But your drilldown will definitely care about this null value. 

This seems to solve all issues. There is an unrelated issue if you have the same variable on multiple scenes, and you select a value on the variable (get's added to URL), then go another app/page (different app), then open the scene app page again, the variable is going to have the same value, but nothing in url state, so when you move to a different scene (via tab or drilldown) then that variable is not going to be part of the url, and that other scene is not going initialize the variable to the same value (because it's not part of url). 

But I think this is a different problem, one we can solve by sharing / caching / restoring state between shared (identical) variables between different scenes. 

@dprokop ^

2023-03-22 14:50 UTC, torkelo commented on packages/scenes/src/services/UrlSyncManager.test.ts
> +      // expect(obj.state.name).toBe('test');
so this is the behavior change, before the UrlSyncManager was able to restore an initial state that it would give the scene object in case the url key was removed. Now this needs to be handled in each scene object

2023-03-23 08:40 UTC, dprokop commented on packages/scenes/src/services/UrlSyncManager.test.ts
> +      // expect(obj.state.name).toBe('test');
think this deserves a note in Changelog with an example snippet what does "handled in each scene object" mean.

2023-03-23 08:40 UTC, dprokop commented on packages/scenes/src/services/UrlSyncManager.test.ts
> +      // expect(obj.state.name).toBe('test');
@torkelo qq - so this basically now needs to be handled using `updateFromUrl`, right?

2023-03-23 09:38 UTC, domasx2 approved these changes
re-tested, now works well :+1:

2023-03-23 09:47 UTC, merged